news_window_days: 3
news_topk: 10

layer_weights:
  company: 1.0
  industry: 0.8
  macro: 0.6

industry_query_tails:
  - 政策
  - 消费数据
  - 价格
  - 行业报告
  - 库存
  - 销量
  - 景气度

macro_keywords:
  - 中国经济
  - 宏观政策
  - 消费政策
  - 监管措施
  - 货币政策
  - 财政政策
  - 房地产政策

macro_query_tails:
  - 数据
  - 走势
  - 指标
  - 报告
  - 解读
source_weights:
  证券日报: 1.15
  第一财经: 1.08

domain_aliases:
  yicai.com: 第一财经
  eastmoney.com: 东方财富
  10jqka.com.cn: 同花顺
  cs.com.cn: 证券时报
  cnstock.com: 上海证券报
  people.cn: 人民网
  xinhuanet.com: 新华社
  stockstar.com: 证券之星
  qq.com: 腾讯网
  sina.com.cn: 新浪财经

priority_keywords:
  - 公告
  - 回购
  - 减持
  - 问询函
  - 年报
  - 中报
  - 集采           
  - 算力
  - 以旧换新

pos_words:
  - 超预期
  - 中标
  - 获批
  - 提价
  - 扩产
  - 订单充足

neg_words:
  - 处罚
  - 问询函
  - 业绩预亏
  - 降价
  - 缺货
  - 限售解禁
# 是否允许用 LLM 来补全“行业→上位词”（命中不到时兜底）
industry_upper_llm_enabled: true
# 自定义 LLM 提示模板（可选）
industry_upper_llm_prompt: "请给出‘{term}’所属的上位行业词，不超过5个，用中文输出，使用逗号分隔，且只输出词本身。"

# 常见行业扩展示例（可继续扩充）
industry_upper_map:
  消费电子: ["电子", "科技", "TMT"]
  光伏: ["新能源", "电力设备"]
  储能: ["新能源", "电力设备"]
  新能源汽车: ["汽车", "新能源"]
  汽车零部件: ["汽车"]
  军工: ["国防军工"]
  光模块: ["通信", "电子", "TMT"]
  通信设备: ["通信", "TMT"]
  云计算: ["计算机", "TMT", "科技"]
  计算机设备: ["计算机", "TMT"]
  传媒: ["传媒互联网", "TMT"]
  游戏: ["传媒互联网", "TMT"]
  教育: ["服务消费"]
  钢铁: ["周期", "原材料"]
  有色金属: ["周期", "原材料"]
  煤炭: ["周期", "能源"]
  石油石化: ["周期", "能源化工"]
  化工: ["周期", "能源化工"]
  机械: ["通用设备", "高端制造"]
  电力设备: ["新能源", "制造业"]
  电网: ["公用事业"]
  航空机场: ["交通运输"]
  航运港口: ["交通运输"]
  物流: ["交通运输"]
  农林牧渔: ["农业", "大消费"]
  家用电器: ["家电", "大消费"]
  社会服务: ["服务消费", "大消费"]
  银行: ["金融"]
  证券: ["金融"]
  保险: ["金融"]
  信托: ["金融"]
  白酒: ["食品饮料", "消费"]
  啤酒: ["食品饮料", "消费"]
  葡萄酒: ["食品饮料", "消费"]
  饮料: ["食品饮料", "消费"]
  食品加工: ["食品饮料", "消费"]
  半导体: ["科技", "TMT"]
  芯片: ["科技", "TMT"]
  计算机应用: ["科技", "TMT"]
  人工智能: ["科技", "TMT"]
  医药生物: ["医药"]
  医疗服务: ["医药", "医药生物"]
  房地产: ["地产", "建筑地产"]

# 宏观事件放大器配置
macro_event_keywords:
  - 国常会
  - 中期借贷便利
  - MLF
  - 降准
  - 降息
  - 地产新政
  - 房贷利率
  - 特别国债
  - 汇率稳定
macro_event_boost: 1.6